# Use an official Node.js image as the base
FROM node:14

# Set the working directory to the Angular app root
WORKDIR /usr/src/app/frontend

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Build the Angular app
RUN ng build --prod

# Expose port 80
EXPOSE 4200

# Start the Angular app
CMD ["npm", "start"]
