version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.express
    ports:
      - '5000:5000'
    environment:
      -   MONGODB_URL=mongodb://mongo:27017/ILEARN
    command: npm run start
    

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.angular
    ports:
      - '4200:4200'
    command: ng serve --host 0.0.0.0

  mongo:
    image: mongo
    ports:
      - '27017:27017'
    environment: 
     MONGO_INITDB_DATABASE: ILEARN