version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.express
    ports:
      - '5000:5000'
    environment:
      -   MONGODB_URL=mongodb://host.docker.internal:27017/ILEARN
    command: npm run start
    

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.angular
    ports:
      - '4200:4200'
    command: ng serve --host 0.0.0.0

  